---
services:
      
  codebase:
    container_name: codebase
    image: alpine:latest
    working_dir: /root/ros_ws/src
    volumes:
      - src:/root/ros_ws/src
    stdin_open: true
    tty: true

  ros_workspace:
    image: ros_workspace:latest
    build:
      context: docker/
    container_name: ros_workspace
    working_dir: /root/ros_ws/src
    environment:
      DISPLAY: ${DISPLAY}
    depends_on:
      - codebase
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - src:/root/ros_ws/src
      - build:/root/ros_ws/build
      - install:/root/ros_ws/install
      - log:/root/ros_ws/log
    stdin_open: true
    tty: true
    networks:
      - ros-network

volumes:
  src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ros_ws/src
  build:
  install:
  log:

networks:
  ros-network:
    driver: bridge

