# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

plugins=(
	git
	zsh-autosuggestions
	zsh-syntax-highlighting
	fast-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh

bindkey '^ ' autosuggest-accept

alias update="sudo apt update && sudo apt upgrade -y"
alias fman="compgen -c | fzf | xargs man"

chpwd_hook() ls
chpwd_functions+=( chpwd_hook )

if [ -d "$HOME"/.zshrc.d ]; then
    for i in "$HOME"/.zshrc.d/*.sh; do
        if [ -f "$i" ]; then
            source "$i"
        fi
    done
    unset i
fi

eval "$(zoxide init --cmd cd zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
